import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { CldUploadWidget } from "next-cloudinary";

export const metadata: Metadata = {
  title: "Olola Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="autumn">
      <body>
        <header>
          <NavBar />
        </header>
        {children}
      </body>
    </html>
  );
}
